// GENERATED by scripts/gen_vocabulary.py from scilink/ui/vocabulary.py — do not edit.
// The Python module is the source; tests/test_vocabulary_sync.py keeps this file in step.
export const VOCAB = {
  "activity_labels": {
    "analyzing": "Analyzing {target}",
    "applying_feedback": "Applying your feedback to the script…",
    "attempt": "Attempt {n} · {label}",
    "candidate": "Candidate {n} · {label}",
    "correcting": "Correcting the script (attempt {n})…",
    "delegating": "Delegating to {target}",
    "escalating": "Escalating to {n} parallel candidates…",
    "executing_code": "Executing analysis code…",
    "executing_code_attempt": "Executing analysis code (attempt {n})…",
    "executing_script": "Executing analysis script…",
    "executing_script_attempt": "Executing analysis script (attempt {n})…",
    "reviewing": "Reviewing {target}",
    "verification": "Verification {i}/{n}…",
    "verification_annealing": "Verification {i}/{n} · annealing level {level}…",
    "visual_qc": "Visual QC · {target}",
    "waiting_for": "Waiting for the {who}…",
    "waiting_for_input": "Waiting for your input…",
    "wrapping_up": "Wrapping up…",
    "writing_code": "Writing analysis code…",
    "writing_code_attempt": "Writing analysis code (attempt {n})…",
    "writing_response": "Writing response…"
  },
  "consent_text": "I understand that the agent will execute generated Python code on my machine",
  "default_activity": "Agent is working…",
  "enter_accepts_hint": "Enter = {accept}",
  "handoff_prefixes": [
    "🧪 Delegating to",
    "📋 Delegating to",
    "⚛️ Delegating to",
    "🧬 Fusing delegations"
  ],
  "modes": {
    "analyze": {
      "autonomy_options": [
        "co-pilot",
        "autopilot",
        "autonomous"
      ],
      "blurb": "Interpret experimental data — images, spectra, hyperspectral cubes — with agentic fitting and reports",
      "description": "Multi-modal data analysis",
      "emoji": "🔬",
      "key": "analyze",
      "label": "Analyze",
      "legacy_prefixes": [],
      "name": "Analyze",
      "placeholder": "Message the analysis agent...",
      "session_prefix": "analysis_session",
      "stop_message": "Analysis stopped by user."
    },
    "meta": {
      "autonomy_options": [
        "autopilot",
        "autonomous"
      ],
      "blurb": "Describe a goal — the meta-agent routes work to the analysis and planning specialists and fuses the results",
      "description": "Routes your research goal to the Analyze & Plan specialists",
      "emoji": "🎛️",
      "key": "meta",
      "label": "🧪 📋 ⚛️",
      "legacy_prefixes": [],
      "name": "Mission Control",
      "placeholder": "Message mission control...",
      "session_prefix": "meta_session",
      "stop_message": "Analysis stopped by user."
    },
    "plan": {
      "autonomy_options": [
        "co-pilot",
        "autopilot",
        "autonomous"
      ],
      "blurb": "Design experiments and optimization campaigns, grounded in your papers, code, and data",
      "description": "Experimental design & optimization",
      "emoji": "📋",
      "key": "plan",
      "label": "Plan",
      "legacy_prefixes": [
        "campaign_session"
      ],
      "name": "Plan",
      "placeholder": "Message the planning agent...",
      "session_prefix": "planning_session",
      "stop_message": "Planning stopped by user."
    },
    "simulate": {
      "autonomy_options": [
        "co-pilot",
        "autopilot",
        "autonomous"
      ],
      "blurb": "Build structures and run DFT/MD simulations end to end",
      "description": "Submit and monitor DFT/MD simulations",
      "emoji": "⚛️",
      "key": "simulate",
      "label": "Simulate",
      "legacy_prefixes": [
        "simulate_session"
      ],
      "name": "Simulate",
      "placeholder": "Message the simulation agent...",
      "session_prefix": "simulation_session",
      "stop_message": "Simulation stopped by user."
    }
  },
  "names": {
    "branch": "Branch",
    "candidate": "Candidate",
    "delegation": "Delegation",
    "judge_pick": "Judge's pick",
    "meta": "Mission control",
    "resume_past": "Resume past session",
    "resume_session": "Resume Session",
    "specialist": "Specialist",
    "start_session": "Start Session",
    "stop": "Stop agent",
    "turn": "Turn",
    "verbose_section": "Verbose output",
    "verbose_toggle": "Show verbose output"
  },
  "status_badges": {
    "awaiting_input": "🟠 awaiting your input",
    "idle": "⚪ idle",
    "running": "🟢 running"
  },
  "status_labels": {
    "awaiting_input": "awaiting your input",
    "idle": "idle",
    "running": "running"
  },
  "thought_mark": "⁣"
} as const;
