"""
ASE runner — emits runnable Python scripts that drive any
``DeployedPotential`` through ASE, for either molecular dynamics
(``task="md"``) or geometry + cell relaxation (``task="relax"``).

This is MD-orchestration code owned by MDSimulationAgent, not an
MLIP concern — which is why it lives next to the agent and the
``DeployedPotential`` contract rather than under ``skills/_shared/``.

One template covers every MLIP backend. The only backend-specific
parts of an ASE script are the calculator import line, the
calculator-construction expression, and the device env var — all
three are data on ``potential.ase_calculator`` (an
``ASECalculatorSpec``). Adding a backend is declaring that spec in
the backend's deploy function; it never means writing a new script
generator here.
"""

import os
from typing import Optional

from ._potential import DeployedPotential


def generate_ase_script(
    potential: DeployedPotential,
    working_dir: str,
    structure_file: str = "system.data",
    task: str = "md",
    timestep: float = 1.0,
    temperature: float = 300.0,
    pressure: Optional[float] = None,
    n_steps: int = 1000,
    output_interval: int = 50,
    device: str = "cuda",
    fmax: float = 0.02,
) -> str:
    """
    Write a runnable ASE driver script (``run_md.py`` for MD,
    ``run_relax.py`` for relaxation) into ``working_dir`` and return
    its path.

    Parameters
    ----------
    potential:
        The deployed potential to drive. Its ``ase_calculator`` spec
        supplies the import + construction; the rest of the script is
        backend-agnostic.
    structure_file:
        Path the generated script reads at run time. Accepts any
        ASE-readable format (CIF, XYZ, EXTXYZ, POSCAR, PDB, …) as
        well as LAMMPS data files (.data/.lammps/.lmp).
    task:
        ``"md"`` — MaxwellBoltzmann init + Langevin (NVT) or NPT
        dynamics, writing a trajectory + thermo log.
        ``"relax"`` — BFGS + FrechetCellFilter geometry+cell
        optimization, writing the relaxed structure + a final
        lattice-parameter readout. ``temperature`` / ``pressure`` /
        ``n_steps`` (as a step cap) still apply where meaningful;
        ``fmax`` is the force convergence threshold.
    """
    if task not in ("md", "relax"):
        raise ValueError(f"task must be 'md' or 'relax', got {task!r}")

    spec = potential.ase_calculator
    el_repr = ", ".join(repr(e) for e in potential.elements)

    # ── shared scaffold: imports, device, structure read, calc attach ──
    header = f'''"""
ASE+{potential.backend} {task.upper()} script -- generated by SciLink.

Potential: {potential.model_name} (backend: {potential.backend})
Elements:  {potential.elements}
Task:      {task}

Run:
    python {{script}}                          # uses default device
    {spec.device_env_var}=cpu python {{script}}    # force CPU
"""
import os
import pathlib
import time

from ase import units
from ase.io import read as _ase_read
{spec.import_line}

ELEMENTS = [{el_repr}]
DEVICE = os.environ.get({spec.device_env_var!r}, {device!r})

# LAMMPS data files are not auto-detected by extension; everything else
# (CIF, XYZ, EXTXYZ, POSCAR, PDB, …) is handled by ase.io.read.
_LAMMPS_EXTS = {{".data", ".lammps", ".lmp"}}


def _load_structure():
    _path = {structure_file!r}
    if pathlib.Path(_path).suffix.lower() in _LAMMPS_EXTS:
        from ase.io.lammpsdata import read_lammps_data
        atoms = read_lammps_data(_path, atom_style="atomic", sort_by_id=True)
        if ELEMENTS:
            # write_lammps_data(masses=True) lets ASE infer real elements from
            # masses on read, so atoms.numbers are true Zs in the typical case.
            # Only fall back to type-index remap if mass-based inference didn't
            # recover the expected element set.
            actual = sorted(set(atoms.get_chemical_symbols()))
            expected = sorted(set(ELEMENTS))
            if actual != expected:
                type_to_sym = {{i + 1: ELEMENTS[i] for i in range(len(ELEMENTS))}}
                nums = atoms.get_atomic_numbers()
                atoms.set_chemical_symbols([type_to_sym[int(n)] for n in nums])
    else:
        atoms = _ase_read(_path)
    return atoms
'''

    if task == "md":
        if pressure is not None:
            dynamics_block = (
                "    from ase.md.npt import NPT\n"
                "    dyn = NPT(\n"
                "        atoms,\n"
                f"        timestep={timestep} * units.fs,\n"
                f"        temperature_K={temperature},\n"
                f"        externalstress={pressure} * units.bar,\n"
                "        ttime=20.0 * units.fs,\n"
                "        pfactor=(2e6 * units.GPa) * (20.0 * units.fs)**2,\n"
                "    )"
            )
        else:
            dynamics_block = (
                "    from ase.md.langevin import Langevin\n"
                "    dyn = Langevin(\n"
                "        atoms,\n"
                f"        timestep={timestep} * units.fs,\n"
                f"        temperature_K={temperature},\n"
                "        friction=0.01,\n"
                "    )"
            )
        body = f'''

def main():
    from ase.io.trajectory import Trajectory
    from ase.md.velocitydistribution import MaxwellBoltzmannDistribution

    atoms = _load_structure()
    print(f"system:  {{len(atoms)}} atoms "
          f"({{sorted(set(atoms.get_chemical_symbols()))}})")
    print(f"device:  {{DEVICE}}")
    atoms.calc = {spec.construct_expr}

    MaxwellBoltzmannDistribution(atoms, temperature_K={temperature})

{dynamics_block}

    traj = Trajectory("traj.traj", "w", atoms)
    dyn.attach(traj.write, interval={output_interval})

    log_file = open("thermo.log", "w")
    log_file.write("# step time(ps) PE(eV) KE(eV) T(K)\\n")
    log_file.flush()

    def log_step():
        epot = atoms.get_potential_energy()
        ekin = atoms.get_kinetic_energy()
        temp = atoms.get_temperature()
        step = dyn.nsteps
        time_ps = step * {timestep} / 1000.0
        line = (f"{{step}} {{time_ps:.4f}} {{epot:.6f}} "
                f"{{ekin:.6f}} {{temp:.2f}}")
        print(line)
        log_file.write(line + "\\n")
        log_file.flush()

    dyn.attach(log_step, interval={output_interval})

    t0 = time.time()
    print(f"running {n_steps} steps...")
    dyn.run({n_steps})
    log_file.close()
    elapsed = time.time() - t0
    print(f"done -- {{elapsed:.1f}}s "
          f"({{1000 * elapsed / max({n_steps}, 1):.2f}} ms/step)")


if __name__ == "__main__":
    main()
'''
        script_name = "run_md.py"

    else:  # task == "relax"
        body = f'''

def main():
    import json
    import numpy as np
    from ase.optimize import BFGS
    from ase.filters import FrechetCellFilter
    from ase.io import write

    atoms = _load_structure()
    print(f"system:  {{len(atoms)}} atoms "
          f"({{sorted(set(atoms.get_chemical_symbols()))}})")
    print(f"device:  {{DEVICE}}")
    atoms.calc = {spec.construct_expr}

    cell0 = atoms.cell.cellpar()
    print(f"initial cellpar: {{np.round(cell0, 4)}}")

    # FrechetCellFilter relaxes atomic positions AND the cell, so the
    # equilibrium lattice constant falls out of the optimization.
    opt = BFGS(FrechetCellFilter(atoms), logfile="relax.log")
    t0 = time.time()
    converged = opt.run(fmax={fmax}, steps={n_steps})
    elapsed = time.time() - t0

    cell1 = atoms.cell.cellpar()
    write("relaxed.xyz", atoms)

    result = {{
        "converged": bool(converged),
        "steps": int(opt.nsteps),
        "fmax_threshold": {fmax},
        "final_energy_eV": float(atoms.get_potential_energy()),
        "initial_cellpar": [float(x) for x in cell0],
        "final_cellpar": [float(x) for x in cell1],
        "lattice_constant_A": float(cell1[0]),
        "elapsed_s": round(elapsed, 2),
    }}
    with open("relax_result.json", "w") as f:
        json.dump(result, f, indent=2)

    print(f"final cellpar:   {{np.round(cell1, 4)}}")
    print(f"lattice constant: {{cell1[0]:.4f}} A")
    print(f"converged: {{converged}}  ({{opt.nsteps}} steps, {{elapsed:.1f}}s)")


if __name__ == "__main__":
    main()
'''
        script_name = "run_relax.py"

    content = (header + body).replace("{script}", script_name)
    os.makedirs(working_dir, exist_ok=True)
    path = os.path.join(working_dir, script_name)
    with open(path, "w") as f:
        f.write(content)
    return path
