"""Agent-driven simulation workflow — Configure → Review → Submit → Monitor."""
from __future__ import annotations

import os
import re
import stat as stat_mod
import tempfile
import textwrap
from datetime import datetime
from pathlib import Path, PurePosixPath
from typing import Any, Dict, List, Optional, Set

import streamlit as st

from scilink.ui.components.wizard_state import (
    apply_lammps_defaults,
    save_lammps,
)


# ══════════════════════════════════════════════════════════════
# Script templates
# ══════════════════════════════════════════════════════════════

def _generate_run_script(
    data_file: str,
    research_goal: str,
    ff_files: Optional[Dict[str, str]],
    lammps_command: str,
    model_name: str,
    base_url: str,
    api_key_env: str,
    max_attempts: int,
    stage_timeout: int,
    container_work_dir: str,
) -> str:
    """Generate the Python script that runs inside the container."""
    ff_dict_str = repr(ff_files) if ff_files else "None"
    base_url_str = repr(base_url) if base_url else "None"     # ← FIX
    # Escape research goal for safe triple-quote embedding
    safe_goal = research_goal.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"Auto-generated by SciLink UI — runs the MD refinement loop inside container.\"\"\"
        import os
        import sys
        import logging
        from pathlib import Path
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s | %(levelname)s | %(message)s",
            datefmt="%H:%M:%S",
            stream=sys.stdout,
        )
        sys.stdout.reconfigure(line_buffering=True)
        logging.info("=" * 60)
        logging.info("SCILINK MD REFINEMENT LOOP — REMOTE RUN")
        logging.info("=" * 60)
        from scilink.agents.sim_agents.simulation_pipeline import run_complete_workflow
        from scilink.agents.sim_agents.refinement import LocalExecutor
        working_dir = Path("{container_work_dir}")
        api_key = os.environ.get("{api_key_env}")
        if not api_key:
            logging.error("API key not found in ${api_key_env}")
            sys.exit(1)
        data_file = "{data_file}"
        research_goal = \"\"\"{safe_goal}\"\"\"
        force_field_files = {ff_dict_str}
        logging.info(f"Data file: {{data_file}}")
        logging.info(f"Force field: {{force_field_files}}")
        logging.info(f"Goal: {{research_goal}}")
        logging.info("")
        # Headless remote node → AUTONOMOUS (no human to consult). The engine
        # binary lives in run_command (config), not in the library.
        results = run_complete_workflow(
            research_goal,
            scale="molecular_dynamics",
            software="lammps",
            structure_file=data_file,
            force_field_files=force_field_files,
            output_dir=str(working_dir),
            api_key=api_key,
            base_url={base_url_str},
            model_name="{model_name}",
            executor=LocalExecutor(timeout={stage_timeout}),
            run_command="{lammps_command} -in {{script}}",
            autonomy="autonomous",
            max_run_cycles={max_attempts},
        )
        logging.info("")
        logging.info("=" * 60)
        logging.info("SIMULATION COMPLETE")
        logging.info("=" * 60)
        import json
        results_file = working_dir / "scilink_results.json"
        try:
            with open(results_file, "w") as f:
                json.dump(results, f, indent=2, default=str)
            logging.info(f"Results written to {{results_file}}")
        except Exception as e:
            logging.warning(f"Could not serialize results: {{e}}")
        logging.info("Output files:")
        for p in sorted(working_dir.iterdir()):
            if p.is_file():
                logging.info(f"  {{p.name}} ({{p.stat().st_size:,}} bytes)")
    """)

def _generate_slurm_script_generic(
    exec_mode: str,
    job_name: str,
    account: str,
    partition: str,
    time_limit: str,
    nodes: int,
    ntasks_per_node: int,
    host_work_dir: str,
    module_commands: str,
    api_key_env: str,
    python_cmd: str,
    # Container-specific
    runtime: str = "",
    image: str = "",
    image_tar: str = "",
    mounts: list[dict] = None,
    extra_runtime_flags: str = "",
    container_work_dir: str = "",
    extra_sbatch: str = "",
) -> str:
    """Generate a SLURM script for any execution mode."""
    mounts = mounts or []

    # ── SBATCH header ─────────────────────────────────────
    lines = [
        "#!/bin/bash",
        f"#SBATCH -J {job_name}",
        f"#SBATCH -t {time_limit}",
        f"#SBATCH -N {nodes}",
        f"#SBATCH --ntasks-per-node={ntasks_per_node}",
        "#SBATCH --cpus-per-task=1",
        f"#SBATCH -o {host_work_dir}/{job_name}_%j.out",
        f"#SBATCH -e {host_work_dir}/{job_name}_%j.err",
    ]
    if account:
        lines.append(f"#SBATCH -A {account}")
    if partition:
        lines.append(f"#SBATCH -p {partition}")
    for extra_line in extra_sbatch.strip().splitlines():
        if extra_line.strip():
            lines.append(f"#SBATCH {extra_line.strip()}")

    lines.append("")
    lines.append('echo "================================================"')
    lines.append(f'echo "SciLink LAMMPS Simulation"')
    lines.append('echo "================================================"')
    lines.append('echo "Job ID: $SLURM_JOB_ID"')
    lines.append('echo "Start: $(date)"')
    lines.append('echo "Host: $(hostname)"')
    lines.append("")

    # ── Module loading ────────────────────────────────────
    if module_commands.strip():
        lines.append("# Environment setup")
        lines.append("source /etc/profile.d/modules.sh 2>/dev/null || true")
        for cmd in module_commands.strip().splitlines():
            if cmd.strip():
                lines.append(cmd.strip())
        lines.append("")

    # ── API key check ─────────────────────────────────────
    lines.append("# Load API key from user environment")
    lines.append("source ~/.bashrc 2>/dev/null || true")
    lines.append(f'if [ -z "${{{api_key_env}}}" ]; then')
    lines.append(f'    echo "ERROR: {api_key_env} not set"')
    lines.append("    exit 1")
    lines.append("fi")
    lines.append('echo "API key: loaded"')
    lines.append("")
    lines.append('echo "STAGE_MARKER: STARTING"')
    lines.append("")

    # ── Execution block (mode-dependent) ──────────────────
    if exec_mode == "Container":
        lines.append("# Container execution")

        # Load image if tar provided
        if image_tar:
            lines.append(f'if ! {runtime} image exists {image} 2>/dev/null; then')
            lines.append(f'    echo "Loading image from {image_tar}..."')
            if runtime in ("podman", "docker"):
                lines.append(f'    {runtime} load -i {image_tar}')
            else:
                # singularity/apptainer use the .sif directly
                pass
            lines.append("fi")
            lines.append("")

        # Build mount flags
        mount_flags = []
        for mnt in mounts:
            h = mnt.get("host", "").rstrip("/")
            c = mnt.get("container", "").rstrip("/")
            mode = mnt.get("mode", "rw")
            if h and c:
                if runtime in ("podman", "docker"):
                    suffix = ":ro" if mode == "ro" else ""
                    mount_flags.append(f"-v {h}:{c}{suffix}")
                else:
                    # singularity/apptainer
                    suffix = ":ro" if mode == "ro" else ""
                    mount_flags.append(f"--bind {h}:{c}{suffix}")

        # Build env flags
        if runtime in ("podman", "docker"):
            env_flag = f"--env {api_key_env}=${{{api_key_env}}}"
        else:
            env_flag = f"--env {api_key_env}=${{{api_key_env}}}"

        # Build run command
        if runtime in ("podman", "docker"):
            cmd_parts = [
                f"{runtime} run --rm",
                f"    {' '.join(mount_flags)}" if mount_flags else "",
                f"    {env_flag}",
                f"    {extra_runtime_flags}" if extra_runtime_flags else "",
                f"    {image}",
                f'    bash -c "{python_cmd} {container_work_dir}/run_simulation.py"',
            ]
        else:
            # singularity / apptainer
            cmd_parts = [
                f"{runtime} exec",
                f"    {' '.join(mount_flags)}" if mount_flags else "",
                f"    {env_flag}",
                f"    {extra_runtime_flags}" if extra_runtime_flags else "",
                f"    {image}",
                f'    bash -c "{python_cmd} {container_work_dir}/run_simulation.py"',
            ]

        lines.append(" \\\n".join(p for p in cmd_parts if p.strip()))

    elif exec_mode.startswith("Direct"):
        lines.append("# Direct execution")
        lines.append(f"cd {host_work_dir}")
        lines.append(f"{python_cmd} {host_work_dir}/run_simulation.py")

    else:
        lines.append("# Custom execution — edit this section")
        lines.append(f"cd {host_work_dir}")
        lines.append(f"{python_cmd} {host_work_dir}/run_simulation.py")

    # ── Footer ────────────────────────────────────────────
    lines.append("")
    lines.append("EXIT_CODE=$?")
    lines.append("")
    lines.append('echo ""')
    lines.append('echo "STAGE_MARKER: FINISHED (exit=$EXIT_CODE)"')
    lines.append('echo "================================================"')
    lines.append('if [ $EXIT_CODE -eq 0 ]; then')
    lines.append('    echo "Simulation completed successfully"')
    lines.append(f'    ls -lh {host_work_dir}/ | head -30')
    lines.append("else")
    lines.append('    echo "Simulation FAILED (exit code: $EXIT_CODE)"')
    lines.append("fi")
    lines.append('echo "End: $(date)"')
    lines.append("exit $EXIT_CODE")

    return "\n".join(lines) + "\n"

# ══════════════════════════════════════════════════════════════
# Log parsing for stage progress
# ══════════════════════════════════════════════════════════════

_STAGE_PATTERNS = [
    (re.compile(r"STAGE_MARKER:\s*STARTING", re.I), "Starting"),
    (re.compile(r"stage\s*\d*\s*:\s*minim", re.I), "Minimization"),
    (re.compile(r"stage\s*\d*\s*:\s*(nvt|npt)?\s*equil", re.I), "Equilibration"),
    (re.compile(r"stage\s*\d*\s*:\s*(nvt|npt)?\s*prod", re.I), "Production"),
    (re.compile(r"running\s+(final\s+)?analysis", re.I), "Analysis"),
    (re.compile(r"SIMULATION\s+COMPLETE", re.I), "Complete"),
    (re.compile(r"STAGE_MARKER:\s*FINISHED.*exit=0", re.I), "Complete"),
    (re.compile(r"STAGE_MARKER:\s*FINISHED", re.I), "Finished (check exit code)"),
]

_STAGE_ORDER = [
    "Starting", "Minimization", "Equilibration",
    "Production", "Analysis", "Complete",
]


def _parse_stage(log_text: str) -> tuple[str, float]:
    """Parse the current stage and progress (0.0–1.0) from log output."""
    current = "Pending"
    for pattern, stage_name in _STAGE_PATTERNS:
        if pattern.search(log_text):
            current = stage_name

    # Calculate progress fraction
    if current in _STAGE_ORDER:
        idx = _STAGE_ORDER.index(current)
        progress = idx / max(len(_STAGE_ORDER) - 1, 1)
    else:
        progress = 0.0

    return current, progress


def _count_errors_warnings(log_text: str) -> tuple[int, int]:
    """Count error and warning lines in log output."""
    errors = len(re.findall(r"^.*(?:ERROR|FAILED|FATAL).*$", log_text, re.M | re.I))
    warnings = len(re.findall(r"^.*(?:WARNING|WARN).*$", log_text, re.M | re.I))
    return errors, warnings


# ══════════════════════════════════════════════════════════════
# Remote file picker (unchanged from previous version)
# ══════════════════════════════════════════════════════════════

_STRUCTURE_EXTENSIONS = {".data", ".lmp"}
_REMOTE_ICONS = {
    ".py": "🐍", ".sh": "⚙️", ".data": "🔬", ".lmp": "🔬",
    ".pdb": "🧬", ".cif": "🧬", ".gro": "🧬",
    ".csv": "📊", ".json": "📋",
    ".txt": "📝", ".log": "📝", ".out": "📝",
    ".prm": "⚛️", ".top": "⚛️", ".itp": "⚛️",
    ".frcmod": "⚛️", ".ff": "⚛️", ".param": "⚛️",
    ".lammps": "⚛️", ".png": "🖼", ".jpg": "🖼",
}


def _render_remote_file_picker(
    label: str,
    key_prefix: str,
    extensions: Optional[set[str]] = None,
    multi: bool = False,
) -> List[str]:
    """Compact remote filesystem browser. Returns selected remote paths."""
    conn = st.session_state.get("hpc_connection")
    if conn is None or not conn.is_connected:
        st.caption("Connect to HPC via the sidebar to browse remote files.")
        return []

    PATH_KEY = f"_rfp_{key_prefix}_path"
    SEL_KEY = f"_rfp_{key_prefix}_selected"

    default_cwd = st.session_state.get("hpc_remote_cwd", "~")
    if default_cwd == "~":
        default_cwd = conn.home_dir()

    if PATH_KEY not in st.session_state:
        st.session_state[PATH_KEY] = default_cwd
    if SEL_KEY not in st.session_state:
        st.session_state[SEL_KEY] = []

    selected: List[str] = st.session_state[SEL_KEY]

    if selected:
        for i, path in enumerate(selected):
            c_name, c_rm = st.columns([5, 1])
            with c_name:
                name = PurePosixPath(path).name
                icon = _REMOTE_ICONS.get(PurePosixPath(path).suffix.lower(), "📄")
                st.caption(f"{icon} `{path}`")
            with c_rm:
                if st.button("✕", key=f"rfp_rm_{key_prefix}_{i}"):
                    selected.pop(i)
                    st.session_state[SEL_KEY] = selected
                    st.rerun()

    c_path, c_up, c_home = st.columns([5, 1, 1])
    with c_path:
        with st.form(key=f"rfp_nav_form_{key_prefix}", clear_on_submit=False):
            typed_path = st.text_input(
                "Path", value=st.session_state[PATH_KEY],
                key=f"_rfp_{key_prefix}_path_input",
                label_visibility="collapsed",
            )
            if st.form_submit_button("Go", width="stretch"):
                if typed_path != st.session_state[PATH_KEY]:
                    st.session_state[PATH_KEY] = typed_path
                    st.rerun()
    with c_up:
        if st.button("⬆", key=f"rfp_up_{key_prefix}"):
            st.session_state[PATH_KEY] = str(
                PurePosixPath(st.session_state[PATH_KEY]).parent
            )
            st.rerun()
    with c_home:
        if st.button("🏠", key=f"rfp_home_{key_prefix}"):
            st.session_state[PATH_KEY] = conn.home_dir()
            st.rerun()

    cwd = st.session_state[PATH_KEY]
    st.caption(f"📂 `{cwd}`")

    try:
        entries = conn.listdir(cwd)
    except Exception as exc:
        st.error(f"Cannot list `{cwd}`: {exc}")
        return selected

    entries.sort(key=lambda e: (
        not (stat_mod.S_ISDIR(e.st_mode) if e.st_mode else False),
        e.filename.lower(),
    ))

    container = st.container(height=240)
    with container:
        has_visible = False
        for entry in entries:
            name = entry.filename
            if name.startswith("."):
                continue
            is_dir = stat_mod.S_ISDIR(entry.st_mode) if entry.st_mode else False
            full_path = f"{cwd.rstrip('/')}/{name}"

            if is_dir:
                has_visible = True
                if st.button(
                    f"📁 {name}/",
                    key=f"rfp_d_{key_prefix}_{cwd}_{name}",
                    width="stretch",
                ):
                    st.session_state[PATH_KEY] = full_path
                    st.rerun()
            else:
                ext = PurePosixPath(name).suffix.lower()
                if extensions and ext not in extensions:
                    continue
                has_visible = True
                icon = _REMOTE_ICONS.get(ext, "📄")
                is_sel = full_path in selected
                size = _fmt_size(entry.st_size) if entry.st_size else ""

                c_f, c_s, c_b = st.columns([4, 1.5, 1])
                with c_f:
                    st.caption(f"**{icon} {name}**" if is_sel else f"{icon} {name}")
                with c_s:
                    st.caption(size)
                with c_b:
                    if is_sel:
                        if st.button("✓", key=f"rfp_u_{key_prefix}_{cwd}_{name}"):
                            selected.remove(full_path)
                            st.session_state[SEL_KEY] = selected
                            st.rerun()
                    else:
                        if st.button("＋", key=f"rfp_s_{key_prefix}_{cwd}_{name}"):
                            if multi:
                                selected.append(full_path)
                            else:
                                selected = [full_path]
                            st.session_state[SEL_KEY] = selected
                            st.rerun()

        if not has_visible:
            st.caption("(empty or no matching files)")

    return selected


def _fmt_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if abs(n) < 1024:
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def _q(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


# ══════════════════════════════════════════════════════════════
# Workflow state machine
# ══════════════════════════════════════════════════════════════

def render_agent_workflow() -> None:
    """Main entry point — dispatches to the current workflow phase."""
    phase = st.session_state.get("hpc_workflow_phase", "configure")

    if phase == "configure":
        _render_configure()
    elif phase == "review":
        _render_review_scripts()
    elif phase == "monitoring":
        _render_monitoring()
    elif phase == "results":
        _render_results()
    else:
        st.session_state.hpc_workflow_phase = "configure"
        st.rerun()


# ══════════════════════════════════════════════════════════════
# Phase 1: Configure
# ══════════════════════════════════════════════════════════════

def _map_host_to_container(host_path: str, mounts: list[dict]) -> str:
    """Map a host path to a container path using the mount list.
    
    Returns the original path if no mount matches (with a warning in logs).
    """
    for mnt in mounts:
        h = mnt.get("host", "").rstrip("/")
        c = mnt.get("container", "").rstrip("/")
        if h and c and host_path.startswith(h):
            return c + host_path[len(h):]
    # No matching mount — return as-is (will fail at runtime)
    return host_path


def _show_path_mapping(
    work_dir: str,
    data_path: Optional[str],
    ff_paths: list[str],
) -> None:
    """Show the user how host paths map into the container."""
    mounts = st.session_state.get("_hpc_mounts", [])
    valid_mounts = [m for m in mounts if m.get("host") and m.get("container")]

    if not valid_mounts:
        st.warning("No volume mounts configured. The container won't see your files.")
        return

    paths_to_check = [("Working dir", work_dir)]
    if data_path:
        paths_to_check.append(("Data file", data_path))
    for fp in ff_paths:
        paths_to_check.append(("FF file", fp))

    all_ok = True
    for label, path in paths_to_check:
        mapped = _map_host_to_container(path, mounts)
        if mapped == path:
            # No mount matched
            st.error(f"⚠️ **{label}**: `{path}` — not covered by any mount!")
            all_ok = False
        else:
            st.caption(f"✅ **{label}**: `{path}` → `{mapped}`")

    if not all_ok:
        st.warning("Add a volume mount that covers the unmapped paths.")

def _render_configure() -> None:
    # Pre-fill infrastructure fields from the last successful Prepare Scripts
    # before any widget is created.
    apply_lammps_defaults()

    st.subheader("🧪 LAMMPS Simulation")

    cfg = st.session_state.get("agent_config", {})
    _model = cfg.get("model", "")
    _has_key = bool(
        cfg.get("api_key")
        or os.environ.get("SCILINK_API_KEY")
        or os.environ.get("OPENAI_API_KEY")
        or os.environ.get("ANTHROPIC_API_KEY")
        or os.environ.get("GOOGLE_API_KEY")
    )
    conn = st.session_state.get("hpc_connection")
    has_hpc = conn is not None and conn.is_connected

    if not has_hpc:
        st.warning("Connect to an HPC cluster via the sidebar to submit simulations.")
        return
    if not _model:
        st.warning("Select a model in the sidebar.")
        return
    if not _has_key:
        st.warning("Provide an API key in the sidebar or as an environment variable.")
        return

    st.caption(f"Model: **{_model}** · HPC: 🟢 **{conn.profile.hostname}**")

    # ── Probe remote environment (cached) ─────────────────
    env = st.session_state.get("hpc_env_probe")
    if env is None:
        from scilink.hpc.probe import probe_remote
        with st.spinner("Probing remote environment…"):
            env = probe_remote(conn)
        st.session_state.hpc_env_probe = env

    # Show what was detected
    with st.expander("🔍 Detected environment"):
        det_c1, det_c2 = st.columns(2)
        with det_c1:
            st.caption(f"**Home:** `{env.home}`")
            if env.scratch:
                st.caption(f"**Scratch:** `{env.scratch}`")
            if env.lammps_binaries:
                st.caption(f"**LAMMPS binaries:** {', '.join(f'`{b}`' for b in env.lammps_binaries)}")
            else:
                st.caption("**LAMMPS binaries:** none found in PATH")
        with det_c2:
            if env.lammps_modules:
                st.caption(f"**LAMMPS modules:** {', '.join(f'`{m}`' for m in env.lammps_modules)}")
            if env.container_runtimes:
                st.caption(f"**Container runtimes:** {', '.join(f'`{r}`' for r in env.container_runtimes)}")
            else:
                st.caption("**Container runtimes:** none found")
        if st.button("🔄 Re-probe", key="hpc_reprobe"):
            st.session_state.hpc_env_probe = None
            st.rerun()

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Execution mode
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    st.markdown("**Execution mode**")

    mode_options = ["Direct (modules / PATH)"]
    if env.container_runtimes:
        mode_options.append("Container")
    mode_options.append("Custom script")

    exec_mode = st.radio(
        "How to run LAMMPS + SciLink on the cluster",
        mode_options,
        horizontal=True,
        key="hpc_exec_mode",
    )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Direct mode config
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    if exec_mode.startswith("Direct"):
        st.markdown("##### LAMMPS setup")

        # Module load commands
        module_default = ""
        if env.lammps_modules:
            module_default = f"module load {env.lammps_modules[0]}"
        module_commands = st.text_area(
            "Module / environment commands (run before LAMMPS)",
            value=module_default,
            placeholder="module load lammps/2024\nmodule load python/3.11",
            height=80,
            key="hpc_module_cmds",
        )

        # LAMMPS binary
        lmp_default = ""
        if env.lammps_binaries:
            lmp_default = f"mpirun {env.lammps_binaries[0]}"
        lammps_command = st.text_input(
            "LAMMPS command",
            value=lmp_default,
            placeholder="mpirun lmp_mpi",
            key="hpc_lammps_cmd",
        )

        # Python with scilink
        python_cmd = st.text_input(
            "Python command (must have scilink importable)",
            value=env.python_path or "python3",
            key="hpc_python_cmd",
        )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Container mode config
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    elif exec_mode == "Container":
        st.markdown("##### Container setup")

        ct_c1, ct_c2 = st.columns(2)
        with ct_c1:
            runtime = st.selectbox(
                "Runtime",
                env.container_runtimes or ["podman", "docker", "singularity", "apptainer"],
                key="hpc_container_runtime",
            )
        with ct_c2:
            image = st.text_input(
                "Image (name, path, or .tar to load)",
                placeholder="localhost/my_image:latest  or  /path/to/image.sif",
                key="hpc_container_image",
            )

        image_tar = ""
        if runtime in ("podman", "docker"):
            image_tar = st.text_input(
                "Image tar file to load (optional, blank if already loaded)",
                placeholder="/path/to/image.tar",
                key="hpc_image_tar",
            )

        # ── Volume mounts (dynamic list) ──────────────────
        st.markdown("**Volume mounts**")
        st.caption("Map host directories into the container")

        MOUNTS_KEY = "_hpc_mounts"
        if MOUNTS_KEY not in st.session_state:
            # Start with one empty mount
            st.session_state[MOUNTS_KEY] = [{"host": "", "container": "", "mode": "rw"}]

        mounts: list[dict] = st.session_state[MOUNTS_KEY]

        mounts_to_remove = []
        for i, mnt in enumerate(mounts):
            mc1, mc2, mc3, mc4 = st.columns([3, 3, 1, 0.5])
            with mc1:
                mnt["host"] = st.text_input(
                    "Host path", value=mnt["host"],
                    placeholder="/home/user/project",
                    key=f"mnt_h_{i}", label_visibility="collapsed",
                )
            with mc2:
                mnt["container"] = st.text_input(
                    "Container path", value=mnt["container"],
                    placeholder="/workspace",
                    key=f"mnt_c_{i}", label_visibility="collapsed",
                )
            with mc3:
                mnt["mode"] = st.selectbox(
                    "Mode", ["rw", "ro"],
                    index=0 if mnt.get("mode", "rw") == "rw" else 1,
                    key=f"mnt_m_{i}", label_visibility="collapsed",
                )
            with mc4:
                if st.button("✕", key=f"mnt_rm_{i}"):
                    mounts_to_remove.append(i)

        if mounts_to_remove:
            for idx in reversed(mounts_to_remove):
                mounts.pop(idx)
            st.session_state[MOUNTS_KEY] = mounts
            st.rerun()

        if st.button("＋ Add mount", key="mnt_add"):
            mounts.append({"host": "", "container": "", "mode": "rw"})
            st.session_state[MOUNTS_KEY] = mounts
            st.rerun()

        lammps_command = st.text_input(
            "LAMMPS command (inside container)",
            placeholder="mpirun lmp_mpi",
            key="hpc_lammps_cmd",
        )

        module_commands = st.text_area(
            "Host-side module commands (before container launch)",
            placeholder=f"module load {runtime}",
            height=60,
            key="hpc_module_cmds",
        )

        extra_runtime_flags = st.text_input(
            f"Extra {runtime} flags",
            placeholder="--userns=keep-id --env MY_VAR=value",
            key="hpc_extra_runtime_flags",
        )

        python_cmd = "python3"  # inside container

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Custom script mode
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    else:
        st.info(
            "In custom mode, you write both scripts yourself. "
            "The generated `run_simulation.py` will still be provided as a starting point."
        )
        lammps_command = st.text_input("LAMMPS command", key="hpc_lammps_cmd")
        module_commands = ""
        python_cmd = "python3"

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Data file
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    st.markdown("**Data file** (LAMMPS `.data`)")

    struct_source = st.radio(
        "Source", ["Browse cluster", "Enter path"],
        horizontal=True, key="hpc_struct_source", label_visibility="collapsed",
    )
    remote_data_path: Optional[str] = None
    if struct_source == "Browse cluster":
        sel = _render_remote_file_picker("data file", "struct", _STRUCTURE_EXTENSIONS)
        if sel:
            remote_data_path = sel[0]
    else:
        remote_data_path = st.text_input(
            "Full path on cluster", placeholder=f"{env.home}/project/system.data",
            key="hpc_manual_data",
        )
        remote_data_path = remote_data_path.strip() if remote_data_path else None

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Force field files
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    st.markdown("**Force field files** (optional)")

    ff_source = st.radio(
        "FF source", ["Browse cluster", "Enter path"],
        horizontal=True, key="hpc_ff_source", label_visibility="collapsed",
    )
    remote_ff_paths: List[str] = []
    if ff_source == "Browse cluster":
        remote_ff_paths = _render_remote_file_picker("FF files", "ff", None, multi=True)
    else:
        ff_manual = st.text_input(
            "Full path(s) on cluster (comma-separated for multiple)",
            placeholder=f"{env.home}/project/ff_params.lammps",
            key="hpc_manual_ff",
        )
        if ff_manual:
            remote_ff_paths = [p.strip() for p in ff_manual.split(",") if p.strip()]

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Working directory
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    default_work_dir = ""
    if remote_data_path:
        default_work_dir = str(PurePosixPath(remote_data_path).parent)

    remote_work_dir = st.text_input(
        "Remote working directory",
        value=default_work_dir,
        placeholder=f"{env.scratch or env.home}/simulations/my_run",
        key="hpc_work_dir",
        help="Where scripts are uploaded and output is written. Defaults to data file's directory.",
    )

    # ── Path mapping preview (container mode) ─────────────
    if exec_mode == "Container" and remote_work_dir:
        _show_path_mapping(remote_work_dir, remote_data_path, remote_ff_paths)

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Research goal
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    research_goal = st.text_area(
        "Research goal", height=100, key="hpc_research_goal",
        placeholder="e.g. Run an NPT equilibration followed by NVT production to compute RDFs.",
    )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # SLURM settings
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    st.markdown("**SLURM settings**")

    sc1, sc2, sc3 = st.columns(3)
    with sc1:
        account = st.text_input("Account (-A)", key="hpc_slurm_account")
        time_limit = st.text_input("Time limit (-t)", value="04:00:00", key="hpc_slurm_time")
    with sc2:
        nodes = st.number_input("Nodes (-N)", value=1, min_value=1, key="hpc_slurm_nodes")
        ntasks = st.number_input("Tasks/node", value=16, min_value=1, key="hpc_slurm_ntasks")
    with sc3:
        job_name = st.text_input("Job name (-J)", value="scilink_lammps", key="hpc_slurm_jname")
        partition = st.text_input("Partition (-p, optional)", key="hpc_slurm_partition")

    extra_sbatch = st.text_area(
        "Extra SBATCH directives (one per line, without `#SBATCH`)",
        key="hpc_extra_sbatch", height=60,
        placeholder="--exclusive\n--mem=0",
    )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Orchestrator settings
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    with st.expander("Orchestrator settings"):
        api_key_env = st.text_input(
            "API key environment variable name",
            value="SCILINK_API_KEY",
            key="hpc_api_key_env",
            help="Name of the env var holding the LLM API key on the cluster",
        )
        oc1, oc2 = st.columns(2)
        with oc1:
            max_attempts = st.number_input(
                "Max stage attempts", value=10, min_value=1, key="hpc_max_attempts",
            )
        with oc2:
            stage_timeout = st.number_input(
                "Stage timeout (s)", value=72000, min_value=60, key="hpc_stage_timeout",
            )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Prepare
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    st.markdown("---")
    can_proceed = bool(remote_data_path) and bool(research_goal.strip()) and bool(remote_work_dir)

    if not can_proceed:
        missing = []
        if not remote_data_path:
            missing.append("data file")
        if not research_goal.strip():
            missing.append("research goal")
        if not remote_work_dir:
            missing.append("working directory")
        st.info(f"Still needed: {', '.join(missing)}")

    if st.button(
        "📝 Prepare Scripts",
        type="primary",
        disabled=not can_proceed,
        key="hpc_prepare_btn",
    ):
        save_lammps()
        # ── Build path mapping for container mode ─────────
        data_exec_path = remote_data_path  # direct mode: same path
        work_exec_path = remote_work_dir
        ff_exec_dict: Optional[Dict[str, str]] = None

        if exec_mode == "Container":
            mounts = st.session_state.get("_hpc_mounts", [])
            data_exec_path = _map_host_to_container(remote_data_path, mounts)
            work_exec_path = _map_host_to_container(remote_work_dir, mounts)

            if remote_ff_paths:
                ff_exec_dict = {}
                for i, rp in enumerate(remote_ff_paths):
                    key = "main" if i == 0 else PurePosixPath(rp).name
                    ff_exec_dict[key] = _map_host_to_container(rp, mounts)
        else:
            if remote_ff_paths:
                ff_exec_dict = {}
                for i, rp in enumerate(remote_ff_paths):
                    key = "main" if i == 0 else PurePosixPath(rp).name
                    ff_exec_dict[key] = rp

        # ── Generate run_simulation.py ────────────────────
        _base_url = cfg.get("base_url") or st.session_state.get("cfg_base_url", "") or ""
        run_script = _generate_run_script(
            data_file=data_exec_path,
            research_goal=research_goal.strip(),
            ff_files=ff_exec_dict,
            lammps_command=lammps_command,
            model_name=_model,
            base_url=_base_url,
            api_key_env=api_key_env,
            max_attempts=int(max_attempts),
            stage_timeout=int(stage_timeout),
            container_work_dir=work_exec_path,
        )

        # ── Generate submit.sh ────────────────────────────
        slurm_script = _generate_slurm_script_generic(
            exec_mode=exec_mode,
            job_name=job_name,
            account=account,
            partition=partition,
            time_limit=time_limit,
            nodes=int(nodes),
            ntasks_per_node=int(ntasks),
            host_work_dir=remote_work_dir,
            module_commands=module_commands,
            api_key_env=api_key_env,
            python_cmd=python_cmd,
            # Container-specific
            runtime=st.session_state.get("hpc_container_runtime", ""),
            image=st.session_state.get("hpc_container_image", ""),
            image_tar=image_tar if exec_mode == "Container" else "",
            mounts=st.session_state.get("_hpc_mounts", []),
            extra_runtime_flags=st.session_state.get("hpc_extra_runtime_flags", ""),
            container_work_dir=work_exec_path if exec_mode == "Container" else "",
            extra_sbatch=extra_sbatch,
        )

        st.session_state.hpc_gen_run_script = run_script
        st.session_state.hpc_gen_slurm_script = slurm_script
        st.session_state.hpc_gen_remote_work_dir = remote_work_dir
        st.session_state.hpc_gen_job_name = job_name
        st.session_state.hpc_workflow_phase = "review"
        st.rerun()

# ══════════════════════════════════════════════════════════════
# Phase 2: Review scripts
# ══════════════════════════════════════════════════════════════

def _render_review_scripts() -> None:
    st.subheader("📝 Review & Submit")
    st.caption("Edit the generated scripts if needed, then submit to the cluster.")

    remote_dir = st.session_state.get("hpc_gen_remote_work_dir", "")
    st.info(f"**Remote working directory:** `{remote_dir}`")

    # Editable scripts
    st.markdown("### `run_simulation.py`")
    run_script = st.text_area(
        "Python script (runs inside container)",
        value=st.session_state.get("hpc_gen_run_script", ""),
        height=350, key="hpc_edit_run_script",
    )

    st.markdown("### `submit.sh`")
    slurm_script = st.text_area(
        "SLURM submission script",
        value=st.session_state.get("hpc_gen_slurm_script", ""),
        height=350, key="hpc_edit_slurm_script",
    )

    st.markdown("---")
    err_slot = st.empty()

    c_submit, c_back = st.columns(2)
    with c_back:
        if st.button("← Back to configure", key="hpc_review_back", width="stretch"):
            st.session_state.hpc_workflow_phase = "configure"
            st.rerun()

    with c_submit:
        if st.button(
            "🚀 Upload & Submit",
            type="primary",
            key="hpc_review_submit",
            width="stretch",
        ):
            conn = st.session_state.get("hpc_connection")
            sched = st.session_state.get("hpc_scheduler")
            if not conn or not conn.is_connected:
                err_slot.error("HPC connection lost. Reconnect via sidebar.")
                return

            try:
                with st.spinner("Uploading scripts and submitting job…"):
                    # Upload run_simulation.py
                    _upload_text(
                        conn, run_script,
                        f"{remote_dir}/run_simulation.py",
                    )
                    # Upload submit.sh
                    _upload_text(
                        conn, slurm_script,
                        f"{remote_dir}/submit.sh",
                    )
                    conn.run(f"chmod +x {_q(remote_dir + '/submit.sh')}", timeout=30)

                    # Submit
                    job_id = sched.submit(f"{remote_dir}/submit.sh", work_dir=remote_dir)

                # Track
                from scilink.hpc.scheduler import HPCJob, JobStatus

                job = HPCJob(
                    job_id=job_id,
                    name=st.session_state.get("hpc_gen_job_name", "scilink_lammps"),
                    status=JobStatus.PENDING,
                    work_dir=remote_dir,
                    script_path=f"{remote_dir}/submit.sh",
                    stdout_file=f"{remote_dir}/{st.session_state.get('hpc_gen_job_name', 'scilink_lammps')}_{job_id}.out",
                    stderr_file=f"{remote_dir}/{st.session_state.get('hpc_gen_job_name', 'scilink_lammps')}_{job_id}.err",
                )

                tracked = st.session_state.get("hpc_tracked_jobs", {})
                tracked[job_id] = job
                st.session_state.hpc_tracked_jobs = tracked
                st.session_state.hpc_monitored_job_id = job_id
                st.session_state.hpc_mon_known_files = set()
                st.session_state.hpc_mon_downloaded_images = {}
                st.session_state.hpc_workflow_phase = "monitoring"

                st.success(f"✅ Submitted job **{job_id}**")
                st.balloons()
                st.rerun()

            except Exception as exc:
                err_slot.error(f"Submission failed: {exc}")


# ══════════════════════════════════════════════════════════════
# Phase 3: Live monitoring
# ══════════════════════════════════════════════════════════════

def _render_monitoring() -> None:
    st.subheader("📡 Live Simulation Monitor")

    job_id = st.session_state.get("hpc_monitored_job_id")
    tracked = st.session_state.get("hpc_tracked_jobs", {})
    sched = st.session_state.get("hpc_scheduler")
    conn = st.session_state.get("hpc_connection")

    if not job_id or job_id not in tracked:
        st.warning("No job to monitor.")
        if st.button("← Back",key="mon_back_nojob"):
            st.session_state.hpc_workflow_phase = "configure"
            st.rerun()
        return

    job = tracked[job_id]
    is_terminal = job.status.is_terminal if hasattr(job.status, "is_terminal") else False
    poll_interval = None if is_terminal else "5s"

    @st.fragment(run_every=poll_interval)
    def _monitor_fragment():
        _conn = st.session_state.get("hpc_connection")
        _sched = st.session_state.get("hpc_scheduler")
        _tracked = st.session_state.get("hpc_tracked_jobs", {})
        _jid = st.session_state.get("hpc_monitored_job_id")

        if not _conn or not _sched or not _jid or _jid not in _tracked:
            return

        _job = _tracked[_jid]

        # ── Refresh status ────────────────────────────────
        try:
            fresh = _sched.status(_jid)
            old_status = _job.status
            # Preserve our stdout/stderr paths
            fresh.stdout_file = fresh.stdout_file or _job.stdout_file
            fresh.stderr_file = fresh.stderr_file or _job.stderr_file
            fresh.work_dir = fresh.work_dir or _job.work_dir
            _tracked[_jid] = fresh
            st.session_state.hpc_tracked_jobs = _tracked
            _job = fresh
        except Exception:
            old_status = _job.status

        # ── Tail stdout ───────────────────────────────────
        stdout_text = ""
        if _job.stdout_file:
            try:
                stdout_text = _conn.read_text(_job.stdout_file, tail=500)
            except Exception:
                # File may not exist yet (job pending)
                pass

        stderr_text = ""
        if _job.stderr_file:
            try:
                stderr_text = _conn.read_text(_job.stderr_file, tail=100)
            except Exception:
                pass

        # ── Parse stage progress ──────────────────────────
        stage, progress = _parse_stage(stdout_text)
        n_errors, n_warnings = _count_errors_warnings(stdout_text)

        # ── Metrics row────────────────────────────────
        m1, m2, m3, m4 = st.columns(4)
        with m1:
            st.metric("Status", f"{_job.status.emoji} {_job.status.value}")
        with m2:
            st.metric("Stage", stage)
        with m3:
            runtime = _job.time_used or "—"
            st.metric("Runtime", runtime)
        with m4:
            if n_errors:
                st.metric("Issues", f"🔴 {n_errors} errors")
            elif n_warnings:
                st.metric("Issues", f"🟡 {n_warnings} warnings")
            else:
                st.metric("Issues", "✅ None")

        # ── Progress bar ──────────────────────────────────
        st.progress(progress, text=f"{stage} — {progress:.0%}")

        # ── Cancel button ─────────────────────────────────
        if not _job.status.is_terminal:
            if st.button("🛑 Cancel job", key="mon_cancel"):
                try:
                    _sched.cancel(_jid)
                    st.toast("Cancel signal sent.")
                except Exception as e:
                    st.error(str(e))

        # ── Tabs: stdout / stderr / output files ──────────
        t_out, t_err, t_files = st.tabs(["stdout", "stderr", "Output Files"])

        with t_out:
            if stdout_text.strip():
                import html as _html
                escaped = _html.escape(stdout_text[-8000:])
                st.iframe(
                    f'<pre id="so" style="height:320px;overflow-y:auto;'
                    f"margin:0;background:#0e1117;padding:10px;"
                    f"border-radius:6px;border:1px solid #333;"
                    f"font-family:monospace;font-size:13px;"
                    f'white-space:pre-wrap;color:#e0e0e0">'
                    f"{escaped}</pre>"
                    f"<script>var e=document.getElementById('so');"
                    f"e.scrollTop=e.scrollHeight;</script>",
                    height=340,
                )
            else:
                st.caption("(no output yet — job may be queued)")

        with t_err:
            if stderr_text.strip():
                st.code(stderr_text[-3000:], language="text")
            else:
                st.caption("(no stderr)")

        with t_files:
            _render_remote_output_files(_conn, _job)

        # Rerun the parent on any status change so the connection-bar
        # job counts (rendered outside this fragment) stay fresh.
        if _job.status != old_status:
            st.rerun(scope="app")

    _monitor_fragment()

    # ── Bottom actions (outside fragment) ─────────────────
    job = tracked[job_id]
    if job.status.is_terminal:
        st.markdown("---")
        c1, c2 = st.columns(2)
        with c1:
            if st.button(
                "📋 View Results",
                type="primary",
                key="mon_to_results",
                width="stretch",
            ):
                st.session_state.hpc_workflow_phase = "results"
                st.rerun()
        with c2:
            if st.button(
                "🔄 New Simulation",
                key="mon_new_sim",
                width="stretch",
            ):
                st.session_state.hpc_workflow_phase = "configure"
                st.rerun()


def _render_remote_output_files(conn, job) -> None:
    """List and display new output files from the remote working directory."""
    if not job.work_dir:
        st.caption("No working directory known.")
        return

    known: Set[str] = st.session_state.get("hpc_mon_known_files", set())
    downloaded_images: Dict[str, bytes] = st.session_state.get(
        "hpc_mon_downloaded_images", {},
    )
    IMAGE_EXTS = {".png", ".jpg", ".jpeg"}

    try:
        entries = conn.listdir(job.work_dir)
    except Exception as exc:
        st.caption(f"Cannot list remote dir: {exc}")
        return

    files = [
        e for e in entries
        if not (stat_mod.S_ISDIR(e.st_mode) if e.st_mode else False)
        and not e.filename.startswith(".")
    ]
    files.sort(key=lambda e: e.filename)

    if not files:
        st.caption("(no output files yet)")
        return

    # Discover new image files and download them
    for entry in files:
        ext = PurePosixPath(entry.filename).suffix.lower()
        full = f"{job.work_dir}/{entry.filename}"
        if ext in IMAGE_EXTS and full not in downloaded_images:
            try:
                data = conn.read_bytes(full)
                downloaded_images[full] = data
                st.session_state.hpc_mon_downloaded_images = downloaded_images
            except Exception:
                pass

    # Show images
    new_images = {
        k: v for k, v in downloaded_images.items()
        if PurePosixPath(k).suffix.lower() in IMAGE_EXTS
    }
    if new_images:
        st.markdown("**Generated plots:**")
        for path, data in new_images.items():
            st.image(data, caption=PurePosixPath(path).name)

    # File listing with download
    st.markdown("**All files:**")
    for entry in files:
        name = entry.filename
        size = _fmt_size(entry.st_size) if entry.st_size else ""
        icon = _REMOTE_ICONS.get(PurePosixPath(name).suffix.lower(), "📄")
        full = f"{job.work_dir}/{name}"

        c_n, c_s, c_dl = st.columns([4, 1.5, 1])
        with c_n:
            st.caption(f"{icon} {name}")
        with c_s:
            st.caption(size)
        with c_dl:
            if full in downloaded_images:
                st.download_button(
                    "⬇", data=downloaded_images[full],
                    file_name=name,
                    key=f"mon_dl_{name}",
                )
            else:
                if st.button("⬇", key=f"mon_fetch_{name}"):
                    try:
                        data = conn.read_bytes(full)
                        downloaded_images[full] = data
                        st.session_state.hpc_mon_downloaded_images = downloaded_images
                        st.rerun()
                    except Exception as exc:
                        st.error(str(exc))


# ══════════════════════════════════════════════════════════════
# Phase 4: Results
# ══════════════════════════════════════════════════════════════

def _render_results() -> None:
    st.subheader("📋 Simulation Results")

    job_id = st.session_state.get("hpc_monitored_job_id")
    tracked = st.session_state.get("hpc_tracked_jobs", {})
    conn = st.session_state.get("hpc_connection")

    if not job_id or job_id not in tracked:
        st.warning("No results to display.")
        if st.button("← Back", key="res_back"):
            st.session_state.hpc_workflow_phase = "configure"
            st.rerun()
        return

    job = tracked[job_id]

    # Status summary
    m1, m2, m3 = st.columns(3)
    with m1:
        st.metric("Final Status", f"{job.status.emoji} {job.status.value}")
    with m2:
        st.metric("Runtime", job.time_used or "—")
    with m3:
        ec = job.exit_code if job.exit_code is not None else "—"
        st.metric("Exit Code", ec)

    # Try to load the results JSON
    if conn and conn.is_connected and job.work_dir:
        results_path = f"{job.work_dir}/scilink_results.json"
        try:
            import json
            raw = conn.read_text(results_path)
            results = json.loads(raw)
            with st.expander("Orchestrator results (JSON)", expanded=False):
                st.json(results)
        except Exception:
            pass

    # Show all downloaded images
    downloaded = st.session_state.get("hpc_mon_downloaded_images", {})
    images = {
        k: v for k, v in downloaded.items()
        if PurePosixPath(k).suffix.lower() in {".png", ".jpg", ".jpeg"}
    }
    if images:
        st.markdown("### Generated Plots")
        for path, data in images.items():
            st.image(data, caption=PurePosixPath(path).name)

    # Download all results as zip
    if conn and conn.is_connected and job.work_dir:
        st.markdown("---")
        if st.button(
            "💾 Download all results as ZIP",
            key="res_download_all",
            type="primary",
        ):
            try:
                import io
                import zipfile

                entries = conn.listdir(job.work_dir)
                buf = io.BytesIO()
                with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
                    for entry in entries:
                        if stat_mod.S_ISDIR(entry.st_mode) if entry.st_mode else False:
                            continue
                        full = f"{job.work_dir}/{entry.filename}"
                        try:
                            data = conn.read_bytes(full)
                            zf.writestr(entry.filename, data)
                        except Exception:
                            pass
                st.download_button(
                    "💾 Save ZIP",
                    data=buf.getvalue(),
                    file_name=f"simulation_{job_id}.zip",
                    mime="application/zip",
                    key="res_zip_download",
                )
            except Exception as exc:
                st.error(f"Failed: {exc}")

    # Navigation
    st.markdown("---")
    c1, c2 = st.columns(2)
    with c1:
        if st.button("🔄 New Simulation", key="res_new", width="stretch"):
            _cleanup_monitoring_state()
            st.session_state.hpc_workflow_phase = "configure"
            st.rerun()
    with c2:
        if st.button("📡 Back to Monitor", key="res_to_mon", width="stretch"):
            st.session_state.hpc_workflow_phase = "monitoring"
            st.rerun()


# ══════════════════════════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════════════════════════

def _upload_text(conn, content: str, remote_path: str) -> None:
    """Upload a string as a remote text file."""
    import tempfile
    with tempfile.NamedTemporaryFile(mode="w", suffix=".tmp", delete=False) as f:
        f.write(content)
        tmp = f.name
    try:
        conn.upload(tmp, remote_path)
    finally:
        os.unlink(tmp)


def _cleanup_monitoring_state() -> None:
    """Clear monitoring-specific session state."""
    for key in [
        "hpc_mon_known_files",
        "hpc_mon_downloaded_images",
        "hpc_gen_run_script",
        "hpc_gen_slurm_script",
        "hpc_gen_remote_work_dir",
        "hpc_gen_job_name",
    ]:
        st.session_state.pop(key, None)
    for k in list(st.session_state.keys()):
        if k.startswith("_rfp_"):
            del st.session_state[k]
