#!/usr/bin/env python3
"""Regenerate ``webui/src/vocabulary.ts`` from ``scilink/ui/vocabulary.py``.

The frontend cannot import Python, so the shared words are exported as one
TypeScript module (a ``.ts`` rather than ``.json`` so vite, tsc and the
``node --experimental-strip-types`` check scripts all load it with no
configuration). ``tests/test_vocabulary_sync.py`` fails when the two drift.

Run from the repository root:  python scripts/gen_vocabulary.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scilink.ui.vocabulary import as_json  # noqa: E402

HEADER = ("// GENERATED by scripts/gen_vocabulary.py from scilink/ui/vocabulary.py"
          " — do not edit.\n"
          "// The Python module is the source; tests/test_vocabulary_sync.py"
          " keeps this file in step.\n")
OUT = ROOT / "webui" / "src" / "vocabulary.ts"


def render() -> str:
    body = json.dumps(as_json(), indent=2, ensure_ascii=False, sort_keys=True)
    return f"{HEADER}export const VOCAB = {body} as const;\n"


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
